### ISSUE TITLE
Benchmarks

### ISSUE THREAD

**Issue by robrix** [robrix/higher-order-effects#7]
Benchmark performance of fused handlers for multiple effects, left- and right-associated binds, heavy uses of `State`, effects above and below `NonDet`, and so on.

**Comment by robrix** [comment]
E.g. https://github.com/joshvera/freemonad-benchmark

**Comment by patrickt** [comment]
These have been started in https://github.com/patrickt/effects-benchmarks

**Comment by robrix** [comment]
The actions (e.g. `go`) can be generic, i.e. constraint-polymorphic (`Member` and friends), while the handlers are concrete (at least for those effects that they handle themselves—they’re polymorphic in any above and below them, as applicable).

**Comment by robrix** [comment]
Yeah, let’s go with that and maybe do benchmarks of `NonDet` &c. over there.
